---
- name: Set up a GeoNetwork server
  hosts: geonetwork
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/default.yml
  roles:
    - common
    - tomcat
    - geonetwork

- name: Set up a PostgreSQL/PostGIS server
  hosts: geonetwork
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/default.yml
  roles:
    - common
    - postgres
