---
- name: This playbook sets up a GeoNetwork server
  hosts: geonetwork
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/default.yml
  roles:
    - common
    - tomcat
    - geonetwork
