---
# to active fact gathering
# to see all properties ansible -m setup postgres
- hosts: all
  tasks: []

- name: Set up a PostgreSQL/PostGIS server Python2
  hosts: postgres
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  roles:
    - common

- name: Set up a PostgreSQL/PostGIS server
  hosts: postgres
  gather_facts: yes
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/default.yml
  vars:
    tomcat_ip: "{{ hostvars[groups['geonetwork'][0]]['ansible_all_ipv4_addresses'][2] }}"
  roles:
    - postgres

- name: Set up a GeoNetwork server Python2
  hosts: geonetwork
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  roles:
    - common

- name: Set up a GeoNetwork server
  hosts: geonetwork
  gather_facts: yes
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/default.yml
  vars:
    db_ip: "{{ hostvars[groups['postgres'][0]]['ansible_all_ipv4_addresses'][2] }}"
  roles:
    - tomcat
    - geonetwork

