---
# to active fact gathering
# to see all properties ansible -m setup postgres
- hosts: all
  tasks: []

- name: Set up a PostgreSQL/PostGIS server Python2
  hosts: postgres
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  vars:
    security_ufw_allowed_incoming_tcp_ports:
    - 5432
  roles:
    - common
    - security

- name: Set up a PostgreSQL/PostGIS server
  hosts: postgres
  gather_facts: yes
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/default.yml
  vars:
    tomcat_ip: "{{ hostvars[groups['geonetwork'][0]]['ansible_all_ipv4_addresses'][2] }}"
  roles:
    - postgres

- name: Set up a GeoNetwork server Python2
  hosts: geonetwork
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  vars:
    security_ufw_allowed_incoming_tcp_ports:
    - 80
  roles:
    - common
    - security

- name: Set up a GeoNetwork server
  hosts: geonetwork
  gather_facts: yes
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/default.yml
  vars:
    db_ip: "{{ hostvars[groups['postgres'][0]]['ansible_all_ipv4_addresses'][2] }}"
    tomcat_ip: "{{ hostvars[groups['geonetwork'][0]]['ansible_all_ipv4_addresses'][2] }}"
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "{{tomcat_ip}} localhost"
        extra_parameters: |
          location /geonetwork {        
            proxy_pass         http://localhost:8080/geonetwork;
            proxy_redirect     off;
            proxy_set_header   Host $http_host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
            proxy_read_timeout 240s;  
            proxy_send_timeout 240s;
            proxy_next_upstream_timeout 300s;
          }
  roles:
    - tomcat
    - geonetwork
    - geerlingguy.nginx
