---

- name: configure ssh demon
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: Restart SSH

- name: ensure service starts on a fresh reboot
  service: name=ssh state=started enabled=yes