- name: installing dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - tomcat8
  - tomcat8-admin

- file: 
    path: "/var/lib/tomcat8/"
    owner: tomcat8
    group: tomcat8
    state: directory
    mode: 0755
    recurse: yes
  register: geonetwork.dir.changed

- file:
    path: "{{ geonetwork_data_dir }}"
    owner: tomcat8
    group: tomcat8
    state: directory
    mode: 0755
    recurse: yes
  register: geonetwork.dir.changed

- file:
    path: "{{ geonetwork_data_dir }}/config-db/"
    owner: tomcat8
    group: tomcat8
    state: directory
    mode: 0755
    recurse: yes
  register: geonetwork.dir.changed

- file:
    path: "{{ geonetwork_data_dir }}/config-node/"
    owner: tomcat8
    group: tomcat8
    state: directory
    mode: 0755
    recurse: yes
  register: geonetwork.dir.changed

- name: create setenv.sh
  copy:
    dest: "/usr/share/tomcat8/bin/setenv.sh"
    content: 'CATALINA_OPTS="-Dgeonetwork.dir={{ geonetwork_data_dir }} -Xms1046M -Xmx1046M"'
    owner: tomcat8
    group: tomcat8
    mode: 0755
  register: geonetwork.dir.changed

- name: restart tomcat8
  service: name=tomcat8 state=restarted
  when: geonetwork.dir.changed
