# move this to a common task
- name: set data directory environment variable in etc environment
  lineinfile: dest=/etc/environment state=present regexp='^geonetwork_dir' line='geonetwork_dir={{ geonetwork_data_dir }}'

- name: installing dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - tomcat8
  - tomcat8-admin

- name: create setenv.sh
  copy:
    dest: "/usr/share/tomcat8/bin/setenv.sh"
    content: "geonetwork_dir={{ geonetwork_data_dir }}"
    force: yes
    owner: tomcat8
    group: tomcat8
    mode: 0755
  notify: restart tomcat

