- name: installing dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - tomcat8
  - tomcat8-admin

- file: 
#    path: "/var/lib/tomcat8/"
    path: "{{ geonetwork_data_dir }}"
    owner: tomcat8
    group: tomcat8
    state: directory
    mode: 0755
    recurse: yes

- name: create setenv.sh
  copy:
    dest: "/usr/share/tomcat8/bin/setenv.sh"
    content: 'CATALINA_OPTS="-Dgeonetwork.dir={{ geonetwork_data_dir }} -Xms1046M -Xmx1046M"'
    owner: tomcat8
    group: tomcat8
    mode: 0755
  notify: restart tomcat
